version: "3.0"

services:
  stars-webapi:
    image: stars-webapi:0.0.1-SNAPSHOT
    expose:
      - "9000"
    ports:
      - "9000"
    environment:
      DB_DEFAULT_URL: jdbc:postgresql://postgres:5432/stars
      DB_DEFAULT_USERNAME: stars-user
      DB_DEFAULT_PASSWORD: stars-password
      APPLICATION_SECRET: alkdflçakjdflçaksjfiljwjerewirieowdsldnflsdnlfsldjfksjklfjewiureiwru
      AKKA_CLUSTER_SERVICE_NAME: stars-webapi
      LOGGER_DEFAULT_LEVEL: debug
      LOGGER_STARS_LEVEL: debug
      LOGGER_AKKA_DISCOVERY_LEVEL: debug
      LOGGER_AKKA_CLUSTER_LEVEL: debug
      LOGGER_AKKA_MANAGEMENT_LEVEL: info
      KAFKA_SERVICE_NAME: kafka
      KAFKA_PRODUCER_HOST: kafka
      KAFKA_PRODUCER_PORT: 9092
      KAFKA_CONSUMER_HOST: kafka
      KAFKA_CONSUMER_PORT: 9092
  simulator:
    image: stars-simulator:0.0.1-SNAPSHOT
    environment:
      LOGGER_STARS_LEVEL: debug
      LOGGER_DEFAULT_LEVEL: debug
      AKKA_DISCOVERY_METHOD: akka-dns
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: stars-password
      POSTGRES_USER: stars-user
      POSTGRES_DB: stars

  ## https://raw.githubusercontent.com/bitnami/bitnami-docker-kafka/3.0.0-debian-10-r29/docker-compose.yml

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    expose:
      - "9092"
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
