#!/bin/sh

env \
DB_DEAULT_DRIVER=org.postgresql.Driver \
DB_DEFAULT_URL=jdbc:postgresql://localhost:5432/stars-simulator \
JDBC_DEFAULTS_SLICK_PROFILE=slick.jdbc.PostgresProfile$ \
sbt 'webapi-impl/runAll'