version: "3.0"

services:
  simulator:
    image: stars-simulator:0.0.1-SNAPSHOT
    environment:
      KAFKA_PRODUCER_HOST: kafka
      KAFKA_CONSUMER_HOST: kafka
    depends_on:
      - kafka

  ## https://raw.githubusercontent.com/bitnami/bitnami-docker-kafka/3.0.0-debian-10-r29/docker-compose.yml
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
